# Generated by Django 6.0.1 on 2026-02-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naxodki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('-create_time',)},
        ),
        migrations.AddField(
            model_name='card',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='class_type',
            field=models.CharField(default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='location',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='card',
            name='specific_features',
            field=models.TextField(blank=True),
        ),
    ]
