# Generated by Django 6.0.1 on 2026-02-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naxodki', '0002_alter_card_options_card_category_id_card_class_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=225),
        ),
    ]
