# Generated by Django 6.0.1 on 2026-02-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naxodki', '0003_card_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(max_length=225, unique=True),
        ),
    ]
