# Generated by Django 6.0.1 on 2026-03-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naxodki', '0004_alter_card_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='specific_features',
        ),
        migrations.AddField(
            model_name='card',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
