# Generated by Django 6.0.1 on 2026-03-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naxodki', '0005_remove_card_specific_features_card_img1_card_img2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='card',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='card',
            name='img3',
        ),
        migrations.AddField(
            model_name='card',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, upload_to='cards/'),
        ),
    ]
