# Generated by Django 6.0.1 on 2026-03-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naxodki', '0006_remove_card_img1_remove_card_img2_remove_card_img3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='class_type',
        ),
        migrations.AddField(
            model_name='card',
            name='item_type',
            field=models.CharField(choices=[('found', 'Найденное'), ('lost', 'Потеренное')], default='found', help_text='Найдено или потеряно', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='activity',
            field=models.BooleanField(default=True, help_text='Активно ли объявление'),
        ),
        migrations.AlterField(
            model_name='card',
            name='author',
            field=models.CharField(help_text='Имя автора объявления', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='category_id',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Все категории'), (1, 'Телефоны'), (2, 'Документы'), (3, 'Животные'), (4, 'Ключи'), (5, 'Одежда'), (6, 'Электроника'), (7, 'Транспорт')], default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='city',
            field=models.CharField(blank=True, help_text='Город', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='content',
            field=models.TextField(blank=True, help_text='Описание предмета'),
        ),
        migrations.AlterField(
            model_name='card',
            name='location',
            field=models.CharField(blank=True, help_text='Место находки/потери', max_length=225),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(help_text='Название предмета', max_length=100),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['category_id', '-create_time'], name='naxodki_car_categor_e74779_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['item_type', '-create_time'], name='naxodki_car_item_ty_08dae2_idx'),
        ),
    ]
