# Generated by Django 6.0.1 on 2026-04-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naxodki', '0007_remove_card_class_type_card_item_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя клиента', max_length=100)),
                ('email', models.EmailField(help_text='Email клиента', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Телефон клиента', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
