# Generated by Django 6.0.1 on 2026-04-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naxodki', '0008_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(help_text='Пароль клиента', max_length=128, null=True),
        ),
    ]
